// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf916WnrgwPZVMNFGkhohVY_Sbvthu-2U',
    appId: '1:737191919791:web:068dae324fc5fdfba9945a',
    messagingSenderId: '737191919791',
    projectId: 'interactive-dictionary-a9af3',
    authDomain: 'interactive-dictionary-a9af3.firebaseapp.com',
    storageBucket: 'interactive-dictionary-a9af3.firebasestorage.app',
    measurementId: 'G-VYT1W507BT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA9qM07G-fXEbEEVWq59m9FmxMMyQVwkE',
    appId: '1:737191919791:android:8e6508b36ad25e82a9945a',
    messagingSenderId: '737191919791',
    projectId: 'interactive-dictionary-a9af3',
    storageBucket: 'interactive-dictionary-a9af3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZTSA3PKOYQgmFJf4XvdeJA-HiDzHRaU8',
    appId: '1:737191919791:ios:0cb309e0c736552fa9945a',
    messagingSenderId: '737191919791',
    projectId: 'interactive-dictionary-a9af3',
    storageBucket: 'interactive-dictionary-a9af3.firebasestorage.app',
    iosBundleId: 'com.example.faseehApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZTSA3PKOYQgmFJf4XvdeJA-HiDzHRaU8',
    appId: '1:737191919791:ios:0cb309e0c736552fa9945a',
    messagingSenderId: '737191919791',
    projectId: 'interactive-dictionary-a9af3',
    storageBucket: 'interactive-dictionary-a9af3.firebasestorage.app',
    iosBundleId: 'com.example.faseehApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf916WnrgwPZVMNFGkhohVY_Sbvthu-2U',
    appId: '1:737191919791:web:2959bc286bffebaea9945a',
    messagingSenderId: '737191919791',
    projectId: 'interactive-dictionary-a9af3',
    authDomain: 'interactive-dictionary-a9af3.firebaseapp.com',
    storageBucket: 'interactive-dictionary-a9af3.firebasestorage.app',
    measurementId: 'G-TYHK6H668Z',
  );
}
